name: Publish Conductor OSS Docker image to ghcr.io
on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Build and Push Container to ghcr.io
        uses: GlueOps/github-actions-build-push-containers@v0.3.7
        with:
          dockerfile: ./docker/server/Dockerfile
          tags: anac

